### ISSUE TITLE
Chipsiden: Visning af chips

### ISSUE THREAD

**Issue by Ronnie1983** [Ronnie1983/Idevent#23]
### Describe why you want this feature
Som bruger med rettigheder, vil jeg gerne kunne se en liste over alle de chips jeg har til rådighed
 
### Describe the solution you'd like
Når jeg er på chipsiden vises en liste af chips som jeg har råderet over, med oplysninger om de enkelte chips.

**Comment by Noitcereon** [comment]
Mangler;
- database forbindelse
- DateTime skal formateres til et kortere format.
- User model mangler (hardcoded)
- Invalid mail i data.

**Comment by Noitcereon** [comment]
Non essential: user Email udskrevet som del af listen.
