### ISSUE TITLE
Event product management side: Liste over boder

### ISSUE THREAD

**Issue by Ronnie1983** [Ronnie1983/Idevent#34]
### Describe why you want this feature
Som bruger med rettigheder vil jeg gerne kunne se en liste over boder (stands).
 
### Describe the solution you'd like
Når jeg ser en liste med boder.
 
### Additional context
Idekort og firmakunde side.
Test: GetEventById, GetStandsByEventId, GetAllStandFunctionalities

**Comment by Noitcereon** [comment]
Deprecated.

**Comment by Noitcereon** [comment]
Mistakes were made (manglede "list" til Event Product Management side).

**Comment by Noitcereon** [comment]
Tests needed:
- GetById (EventManager)
- GetAllByEventId (EventStandManager)
