### ISSUE TITLE
Eventsiden: Tilføj

### ISSUE THREAD

**Issue by Ronnie1983** [Ronnie1983/Idevent#42]
### Describe why you want this feature
Som bruger vil jeg gerne tilføje et event
 
### Describe the solution you'd like
Når jeg trykker på Add knappen bliver jeg prompted med oplysninger der ksal udfyldes, og her gemmer jeg et nyt event.

**Comment by Noitcereon** [comment]
Da det er blevet overset at dette issue indebærer at oprette et event (udover kun navigationen) åbner jeg dette issue igen og går i gang med det i sprint 4.
