### ISSUE TITLE
Add Chip side: Chip input

### ISSUE THREAD

**Issue by Ronnie1983** [Ronnie1983/Idevent#68]
### Describe why you want this feature
Som bruger vil jeg gerne kunne indtaste oplysninger om en chip.
 
### Describe the solution you'd like
Følgende skal kunne opdateres:
UID (on chip) - textfelt
Validity period - from/to datetime input
User Email - Textinput (optional)  
Choose company - Dropdown
Choose event (optional)
Event Products (hvert produkt har et input felt som der kan lægges til og fra)
![image](https://user-images.githubusercontent.com/40148361/140297455-becd7686-e0ec-41b0-ae09-4ebae9899939.png)

Ny chip gruppe (optional)
Chip group - dropdown (default group)

**Comment by Noitcereon** [comment]
Limited testing was done (only the navigation test still is on). Therefore the Needs Test is still on this issue.
The testing I did only succeeds when debugging, presumably because of Blazors rendering.
